//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperaMobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperaMobile.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application usage may result in additional charges from your wireless provider..
        /// </summary>
        public static string AdditionalCharges {
            get {
                return ResourceManager.GetString("AdditionalCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured while creating new process. Check your unlock state..
        /// </summary>
        public static string CreateProcessError {
            get {
                return ResourceManager.GetString("CreateProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will delete the whole Opera folder, including your settings and saved personal data.
        /// </summary>
        public static string FolderDeletion {
            get {
                return ResourceManager.GetString("FolderDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have root access set up for this application. You can do this by using Full Unlocked ROMs or WP7 Root Tools by Heathcliff74..
        /// </summary>
        public static string NoRootAccess {
            get {
                return ResourceManager.GetString("NoRootAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera is a property of Opera Software ASA. Neither Opera Software nor author of this launcher are responsible for any damage caused by using this launcher.
        ///
        ///Application usage may result in additional charges from your wireless provider.
        ///
        ///Please, notice that under certain circumstances application may continue to work in background. Use &quot;Exit&quot; function..
        /// </summary>
        public static string OperaProperty {
            get {
                return ResourceManager.GetString("OperaProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera Mobile is a property of Opera Software ASA. 
        ///Only for non-commercial purposes.
        /// </summary>
        public static string OperaProperty2 {
            get {
                return ResourceManager.GetString("OperaProperty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other tasks:.
        /// </summary>
        public static string OtherTasks {
            get {
                return ResourceManager.GetString("OtherTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is provided &quot;AS IS&quot; without any warranties. Author isn&apos;t responsible for any damage caused by application usage.
        /// </summary>
        public static string PageAboutNotice {
            get {
                return ResourceManager.GetString("PageAboutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, note:.
        /// </summary>
        public static string PleaseNote {
            get {
                return ResourceManager.GetString("PleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to remove all Opera files from my device..
        /// </summary>
        public static string RemoveAllOperaFiles {
            get {
                return ResourceManager.GetString("RemoveAllOperaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove Opera work folder.
        /// </summary>
        public static string RemoveFolders {
            get {
                return ResourceManager.GetString("RemoveFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks:.
        /// </summary>
        public static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD2Owner - for graphics.
        ///Heathcliff74 - for policy unlock.
        /// </summary>
        public static string SpecialThanksText {
            get {
                return ResourceManager.GetString("SpecialThanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera starts in....
        /// </summary>
        public static string StartsIn {
            get {
                return ResourceManager.GetString("StartsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching is cancelled.
        ///Press &quot;run&quot; to start Opera again..
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do with Opera?.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
